### ISSUE TITLE
Crash on android trackEvent

### ISSUE THREAD

**Issue by rogerOlier** [AppsFlyerSDK/Unity#28]
Hi,
The function trackEvent crashes on android with
`AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lcom/appsflyer/AppsFlyerLib;.trackEvent(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;Ljava/lang/String;)V"
                                        java.lang.NoSuchMethodError: no non-static method "Lcom/appsflyer/AppsFlyerLib;.trackEvent(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;Ljava/lang/String;)V"
                                            at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                            at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                            at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
                                          at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
                                          at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.Strin`

**Comment by SamiSdd** [comment]
I/Unity   (12600): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='trackEvent' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;)V' in class Lcom/appsflyer/AppsFlyerLib;
I/Unity   (12600): java.lang.NoSuchMethodError: no method with name='trackEvent' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;)V' in class Lcom/appsflyer/AppsFlyerLib;
I/Unity   (12600): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   (12600): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity   (12600): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
I/Unity   (12600):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
I/Unity   (12600):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
I/Unity   (12600):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   (12600):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass


Having same issue

**Comment by SamiSdd** [comment]
ahh Finally found the problem.

@rogerOlier your is bit different. Please update by downloading the source as zip.
Mine is altogether different. It seems that trackEvent in AppsFlyerLib.class have changed parameters it now expect 3rd argument to be Map<string, object>
