### ISSUE TITLE
Android enableUninstallTracking(string) incorrect function

### ISSUE THREAD

**Issue by rtracey07** [AppsFlyerSDK/Unity#68]
The AppsFlyer.enableUninstallTracking(string) function points to AF.updateServerUninstallToken() with incorrect params for that function.

**Comment by WarlordGrey** [comment]
Hello. I'm trying to use AppsFlyer with app on Unity and want to track unistalls.
I saw that you released new method (AppsFlyer.enableUninstallTracking(string) for this (android version) but you didn't update your AppsFlyerUnitySampleApp.
I was a little confused with new method's param "senderId". Is it GCM server key or what?

**Comment by hinews** [comment]
Uninstall tracking don't working with unity plugin on android device.

'adb logcat' contains error:
`
I/Unity (30575): AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='updateServerUninstallToken' signature='(Ljava/lang/String;)V' in class Ljava.lang.Object;
I/Unity (30575): java.lang.NoSuchMethodError: no non-static method with name='updateServerUninstallToken' signature='(Ljava/lang/String;)V' in class Ljava.lang.Object;
I/Unity (30575): at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source)
I/Unity (30575): at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity (30575): at com.unity3d.player.UnityPlayer.c(Unknown Source)
I/Unity (30575): at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
I/Unity (30575): at android.os.Handler.dispatchMessage(Handler.java:98)
I/Unity (30575): at android.os.Looper.loop(Looper.java:146)
I/Unity (30575): at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
I/Unity (30575): at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
I/Unity (30575): at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
I/Unity (30575): at UnityEngine.AndroidReflection.GetMethodMember (Int
`
AppsFlyerUnityPlugin_v4.14.3

**Comment by takaaptech** [comment]
I had it too, non-static method with name update server uninstall token
In Android, should we call AppsFlyer.setAppID("package_name_here"); ?

Because as I know the game can get package name on android itself
